log:
  name: TextCNN
  log_dir: logs
data:
  name: Khan
  root_dir: /share/tongxiao/graduation-project
  data_dir: data
  subtitle_dir: data/subtitles
  video_dir: data/videos
  sample_dir: data/samples
  stopwords: data/NLTK_stopwords.txt
  id2labels: data/Khan.id2labels.pkl
  hierarchy: data/Khan.hierarchy.pkl
  index2know: data/Khan.index2know.pkl
  word2vec: data/word2vec/glove.6B.100d.txt
  model_save_dir: models
  model_name: TextCNN_ResNet.Khan.model
  num_classes: 398
  num_classes_list: [6, 42, 350]

model:
  epochs: 20
  batch_size: 12
  pad_word: <unk>
  max_seq_len: 300
  word_embedding_dim: 100
  out_channel: 100
  kernel_size: [2, 3, 4]
  learning_rate: 0.001
  alpha: 0.5
  dropout: 0.5
  threshold: 0.5

device: "cuda:1"
