log:
  name: VENet
  log_dir: logs
data:
  name: Khan
  root_dir: /share/tongxiao/graduation-project
  data_dir: data
  subtitle_dir: data/subtitles
  video_dir: data/videos
  # only on video segments which are preprocessed by wangxin's algorithm
  sample_dir: data/wangxin_samples
  stopwords: data/NLTK_stopwords.txt
  id2labels: data/Khan.id2labels.pkl
  hierarchy: data/Khan.hierarchy.pkl
  index2know: data/Khan.index2know.pkl
  word2vec: data/word2vec/glove.6B.100d.txt
  model_save_dir: models
  model_name: VENet_2.Khan.model
  num_classes: 398
  num_classes_list: [6, 42, 350]

model:
  epochs: 20
  batch_size: 8
  pad_word: <unk>
  max_seq_len: 200
  word_embedding_dim: 100

  # text lstm
  text_lstm_dim: 100

  # vlstm & hlstm
  fig_lstm_dim: 100

  # fig cnn
  in_channels: 3
  out_channels: 100
  kernel_sizes: [5, 3]
  maxpool_sizes: [3, 3]

  # fusion cnn
  d_2: 100
  fusion_kernels: [1, 3, 5]

  fc_dim: 256
  learning_rate: 0.0001
  alpha: 0.5
  dropout: 0.5
  threshold: 0.5

count: 2

device: "cuda:0"
